import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

interface FormData {
  id: string;
  title: string;
  content: string;
}
const Home: NextPage = () => {
  const [form, setForm] = useState<FormData>({
    id: "",
    title: "",
    content: "",
  });

  async function create(data: FormData) {
    try {
      fetch("http://localhost:3000/api/create", {
        body: JSON.stringify(data),
        headers: {
          contentType: "application/json",
        },
        method: "POST",
      }).then(() => setForm({ title: "", content: "", id: "" }));
    } catch (error) {
      console.log(error);
    }
  }

  const handleSubmit = (data: FormData) => {
    try {
      create(data);
    } catch (error) {
      console.log(error);
    }
  };
  return (
    <>
      <Head>
        <title>Notes App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="mt-4 text-center text-2xl font-bold">Notes</h1>
      <form
        onSubmit={(e) => {
          e.preventDefault();
          handleSubmit(form);
        }}
        className="mix-w-[25%] mx-auto flex w-auto max-w-min flex-col items-stretch space-y-6"
      >
        <input
          type="text"
          placeholder="Title"
          value={form.title}
          onChange={(e) => setForm({ ...form, title: e.target.value })}
          className="rounded border-2 border-gray-600 p-1"
        />
        <textarea
          placeholder="Content"
          value={form.content}
          onChange={(e) => setForm({ ...form, content: e.target.value })}
          className="rounded border-2 border-gray-600 p-1"
        />
        <button type="submit" className="rounded bg-blue-500 p-1 text-white">
          Add +
        </button>
      </form>
    </>
  );
};

export default Home;
